config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :buttons
  # Server websocket cable requests in-process
  #mount ActionCable.server => '/cable'
  
  get 'shops/counter', as: :shop_counter
  get 'shops/coffee', as: :shop_coffee
  get 'shops/print', as: :shop_print
  get 'shops/orders', as: :shop_orders
  get 'shops/ready', as: :shop_ready
  get 'shops/check', as: :shop_check
  get 'shops/new', as: :shop_new
  get 'shops/admin', as: :shop_admin 
  get 'orders/new/:person_id', to: 'orders#new', as: :new_order
  post 'orders/submit', to: 'orders#submit', as: :order_submit
  resources :orders, :except => [:new]
  resources :drinks
  resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'shops#counter'
end

app/models/button.rb
class Button < ApplicationRecord
end

app/controllers/buttons_controller.rb
class ButtonsController < ApplicationController
  before_action :set_button, only: [:show, :edit, :update, :destroy]

  # GET /buttons
  # GET /buttons.json
  def index
    @buttons = Button
               .order(:group, :seq, :name)
  end

  # GET /buttons/1
  # GET /buttons/1.json
  def show
  end

  # GET /buttons/new
  def new
    @button = Button.new
  end

  # GET /buttons/1/edit
  def edit
  end

  # POST /buttons
  # POST /buttons.json
  def create
    @button = Button.new(button_params)

    respond_to do |format|
      if @button.save
        format.html { redirect_to @button, notice: 'Button was successfully created.' }
        format.json { render :show, status: :created, location: @button }
      else
        format.html { render :new }
        format.json { render json: @button.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buttons/1
  # PATCH/PUT /buttons/1.json
  def update
    respond_to do |format|
      if @button.update(button_params)
        format.html { redirect_to @button, notice: 'Button was successfully updated.' }
        format.json { render :show, status: :ok, location: @button }
      else
        format.html { render :edit }
        format.json { render json: @button.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buttons/1
  # DELETE /buttons/1.json
  def destroy
    @button.destroy
    respond_to do |format|
      format.html { redirect_to buttons_url, notice: 'Button was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_button
      @button = Button.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def button_params
      params.require(:button).permit(:name, :group, :enable, :seq)
    end
end

app/helpers/buttons_helper.rb
module ButtonsHelper
end

app/views/buttons/_form.html.erb
<%= form_for(button) do |f| %>
  <% if button.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(button.errors.count, "error") %> prohibited this button from being saved:</h2>

      <ul>
      <% button.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :group %>
    <%= f.text_field :group %>
  </div>

  <div class="field">
    <%= f.label :enable %>
    <%= f.text_field :enable %>
  </div>

  <div class="field">
    <%= f.label :seq %>
    <%= f.number_field :seq %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buttons/edit.html.erb
<h1>Editing Button</h1>

<%= render 'form', button: @button %>

<%= link_to 'Show', @button %> |
<%= link_to 'Back', buttons_path %>

app/views/buttons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buttons</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Group</th>
      <th>Enable</th>
      <th>Seq</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buttons.each do |button| %>
      <tr>
        <td><%= button.id %></td>
        <td><%= button.name %></td>
        <td><%= button.group %></td>
        <td><%= button.enable %></td>
        <td><%= button.seq %></td>
        <td><%= link_to 'Show', button %></td>
        <td><%= link_to 'Edit', edit_button_path(button) %></td>
        <td><%= link_to 'Destroy', button, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Button', new_button_path %>

app/views/buttons/new.html.erb
<h1>New Button</h1>

<%= render 'form', button: @button %>

<%= link_to 'Back', buttons_path %>

app/views/buttons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @button.name %>
</p>

<p>
  <strong>Group:</strong>
  <%= @button.group %>
</p>

<p>
  <strong>Enable:</strong>
  <%= @button.enable %>
</p>

<p>
  <strong>Seq:</strong>
  <%= @button.seq %>
</p>

<%= link_to 'Edit', edit_button_path(@button) %> |
<%= link_to 'Back', buttons_path %>