config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :buttons
  # Server websocket cable requests in-process
  #mount ActionCable.server => '/cable'
  
  get 'shops/counter', as: :shop_counter
  get 'shops/coffee', as: :shop_coffee
  get 'shops/print', as: :shop_print
  get 'shops/orders', as: :shop_orders
  get 'shops/ready', as: :shop_ready
  get 'shops/check', as: :shop_check
  get 'shops/new', as: :shop_new
  get 'shops/admin', as: :shop_admin 
  get 'orders/new/:person_id', to: 'orders#new', as: :new_order
  post 'orders/submit', to: 'orders#submit', as: :order_submit
  resources :orders, :except => [:new]
  resources :drinks
  resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'shops#counter'
end

app/models/person.rb
class Person < ApplicationRecord
    has_many :orders, dependent: :destroy
#    has_many :drinks, through: :orders
    
    #before_destroy :ensure_not_referenced_by_orders
    
    #private
    #    #ensure that there are no order items relating to this person
    #    def ensure_not_referenced_by_orders
    #        unless orders.empty?
    #            errors.add(:base, 'Orders persent for this person')
    #            throw :abort
    #        end
    #    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
    #logger.debug "@people: " + @people.inspect
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        ActionCable.server.broadcast("newperson_channel", message: [@person])
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    respond_to do |format|
      if @person.destroy
        format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to people_url, notice: 'Person not destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :lastdrink)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :lastdrink %>
    <%= f.text_field :lastdrink %>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<!--
<%= link_to 'Show', @person %> |
-->
<%= link_to 'Destroy', @person, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People
<button><%= link_to 'counter', shop_counter_path %></button>
<button><%= link_to 'brewster', shop_new_path %></button><br>
</h1>

<input type="text" id="myInput" onkeyup="myFunctionPeople()" placeholder="Filter name list .." title="Type in characters to reduce name list">
<div id="showAdd" onclick="addPerson();" style="display: none;">Put Add Person Button here</div>
<ul id="myUL">
    <% @people.each do |person| %>
      <li><%= link_to person.name, edit_person_path(person) %></li>
    <% end %>
</ul>
<!--
<h1>Original Listing</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last Drink Id</th>
      <th>Last Drink</th>
      <th>Last Drink Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.lastdrinkid %></td>
        <td><%= person.lastdrink %></td>
        <td><%= person.lastdrinktime %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>
-->

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>
<p>
  <strong>lastdrinkid:</strong>
  <%= @person.lastdrinkid %>
</p>
<p>
  <strong>lastdrinktime:</strong>
  <%= @person.lastdrinktime %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>