config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :buttons
  # Server websocket cable requests in-process
  #mount ActionCable.server => '/cable'
  
  get 'shops/counter', as: :shop_counter
  get 'shops/coffee', as: :shop_coffee
  get 'shops/print', as: :shop_print
  get 'shops/orders', as: :shop_orders
  get 'shops/ready', as: :shop_ready
  get 'shops/check', as: :shop_check
  get 'shops/new', as: :shop_new
  get 'shops/admin', as: :shop_admin 
  get 'orders/new/:person_id', to: 'orders#new', as: :new_order
  post 'orders/submit', to: 'orders#submit', as: :order_submit
  resources :orders, :except => [:new]
  resources :drinks
  resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'shops#counter'
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  # GET /shops/admin
  def admin
  end

  # GET /shops/counter
  # GET /shops/counter.json
  def counter
    @people = Person
              .order("lower(name)")
    logger.debug "@people: " + @people.inspect
    @drinks = Drink.all
    @buttons = Button
               .order(:group, :seq, :name)
  end

  # GET /shops/orders
  # GET /shops/orders.json
  def orders
    @orders = Order
              .includes(:person)
              .order(:id)
              .reverse_order
#              .where("status != ?", "done")

 
    logger.debug "@orders: " + @orders.inspect
    
    @statusList = Order
              .select(:status)
              .distinct
    logger.debug "@statusList: " + @statusList.inspect
  end

  # GET /shops/ready
  # GET /shops/ready.json
  def ready
    hostwithport = "#{request.host_with_port}"
    logger.debug hostwithport
    #   a10e513aab9647cfae2f94b7015f74e7.vfs.cloud9.us-east-1.amazonaws.com
    #   drinks.mikebarb.net
    if hostwithport == "drinks.mikebarb.net" 
      hostwithport = "gcc.org.au/drinks"
    end
    @myUrl = "#{request.protocol}" + hostwithport
    @readyorders = Order
              .where("updated_at > ?", 24.hours.ago)
              .includes(:person)
              .order(:id)

              #.where("updated_at > ? AND status = ?", 24.hours.ago, "ready")

    logger.debug "@readyorders: " + @readyorders.inspect
    
    @statusList = ["ready"]
    logger.debug "@statusList: " + @statusList.inspect
    @readydisplay = true
  end

  # GET /shops/check
  # GET /shops/check.json
  def check
    @readyorders = Order
              .where("updated_at > ?", 24.hours.ago)
              .includes(:person)
              .order(:id)

              #.where("updated_at > ? AND status = ?", 24.hours.ago, "ready")


    logger.debug "@readyorders: " + @readyorders.inspect
    
    @statusList = ["ready", "new"]
    logger.debug "@statusList: " + @statusList.inspect
    @checkdisplay = true
  end

  # GET /shops/new
  # GET /shops/new.json
  def new
    @orders = Order
              .where('updated_at > ?', 24.hours.ago)
              .includes(:person)
              .order(:id)

    @drinks = Drink.all

    @orderscount = Order.group(:drink).count
              #.where("status == ?", "new")
              #.includes(:drink)

    @statusList = ["new", "ready", "done"]
  end
  
  # GET /shops/coffee
  # GET /shops/coffee.json
  def coffee
    @orders = Order
              .where('updated_at > ?', 24.hours.ago)
              .includes(:person)
              .order(:id)

    @drinks = Drink.all

    @orderscount = Order.group(:drink).count
              #.where("status == ?", "new")
              #.includes(:drink)

    @statusList = ["new", "ready", "done"]
  end
  
  # GET /shops/print
  # GET /shops/print.json
  def print
    # this controller simply triggers a simple page 
    # used for printing lables.
    # This page listens for and processes websocket streamed info.
    logger.debug "-----------------------------------------------------"
    logger.debug "entering shops controller"
    logger.debug "parms: " + params.inspect
    #logger.debug "-----------------------------------------------------"
    # Store in session parametes stuff that needs to be kept.
    count = session[:count] || 0
    count += 1
    session[:count] = count
    logger.debug "count: " + count.inspect
    client_id = "269084671189-flp3v3aoifa6apfio4mcgh16ck3sq909.apps.googleusercontent.com"
    client_secret = "cyHu8PqkWpgc0TsClH1fHkcw"
    client_redirect_url = "https://drinks-micmac.c9users.io/shops/print"
    printer_id = '148e56bc-0d7a-642b-9ce3-ba973c3244e9'
    mycode = params[:code]
    logger.debug "mycode: " + mycode.inspect
    myfileName = "tmp/printobject.txt"
    logger.debug "load client from file - first load - occurs if file exists"
    if File::exist?(myfileName) then
        myfile = File.new(myfileName, "r")
        client = Marshal.load(myfile)
        logger.debug "client reloaded: " + client.inspect
        myfile.close
    end
    if(!client) then
      client = CloudPrint::Client.new(client_id: client_id,
                                    client_secret: client_secret
                                    #refresh_token: '4/AWhSyX8Wp4Fasyb66P2AmpCu4ftYZOrzDGqlcLQV70M'
                                    #access_token: 'ya29.GlsiBZhJQxEXzOJYDB4rghj2Jh7az_3marTOrDcI7otsNykHr9YoE38QljaZrU_2KiZOcOb33YBIxv9zL8XJs4MRuWYgfZMQniptY4Rc8woLBE7HD_AXARsmfmia'
                                    )
      @authorize_url = client.auth.generate_url(client_redirect_url)
      logger.debug "0-client: " + client.inspect
      logger.debug "@authorize_url: " + @authorize_url.inspect
      logger.debug "-----------------------------------------------------"
      logger.debug "dumped client to file - no initial file"
      myfile = File.new(myfileName, "w")
      Marshal.dump(client, myfile)
      myfile.close
      logger.debug "About to call render!!! - user will need to authorize the printer"
      render :print and return
    end
    if (mycode) then
      logger.debug "-------------------------- in mycode --------------"
      #if File::exist?(myfileName) then
      #  myfile = File.new(myfileName, "r")
      #  client = Marshal.load(myfile)
      #  logger.debug "client reloaded: " + client.inspect
      #  myfile.close
      #end
      logger.debug "3-client: " + client.inspect
      begin
        refresh_token = client.auth.generate_token(mycode, client_redirect_url)
      rescue
        flash[:notice] = "error processing client.auth.generate_token." 
        # assume that if there is no token && there has been no code in the
        # parameters, then we need to start from scratch building the client
        # and getting the authorisation code.
        client = CloudPrint::Client.new(client_id: client_id,
                                    client_secret: client_secret
                                    #refresh_token: '4/AWhSyX8Wp4Fasyb66P2AmpCu4ftYZOrzDGqlcLQV70M'
                                    #access_token: 'ya29.GlsiBZhJQxEXzOJYDB4rghj2Jh7az_3marTOrDcI7otsNykHr9YoE38QljaZrU_2KiZOcOb33YBIxv9zL8XJs4MRuWYgfZMQniptY4Rc8woLBE7HD_AXARsmfmia'
                                    )
        logger.debug "1-client: " + client.inspect
        logger.debug "-----------------------------------------------------"
        @authorize_url = client.auth.generate_url(client_redirect_url)
        logger.debug "@authorize_url: " + @authorize_url.inspect
        logger.debug "2-client: " + client.inspect
        logger.debug "dumped client to file - initial no code block"
        myfile = File.new(myfileName, "w")
        Marshal.dump(client, myfile)
        myfile.close
        logger.debug "About to call render!!! - user will need to authorize the printer"
        render :print and return
      end
      # If we get here, then we must have a got back a refresh token from the 
      # swap the exchange suthorization code for token call 
      # i.e. client.auth.generate_token.
      logger.debug "refresh_token: " + refresh_token.inspect
      logger.debug "-----------------------------------------------------"
      logger.debug "3a-client: " + client.inspect
      logger.debug "-----------------------------------------------------"
      if (refresh_token) then
        logger.debug "token present - set up client with token for doing print operations"
        client = CloudPrint::Client.new(client_id: client_id,
                                      client_secret: client_secret,
                                      refresh_token: refresh_token
                                      #access_token: 'ya29.GlsiBZhJQxEXzOJYDB4rghj2Jh7az_3marTOrDcI7otsNykHr9YoE38QljaZrU_2KiZOcOb33YBIxv9zL8XJs4MRuWYgfZMQniptY4Rc8woLBE7HD_AXARsmfmia'
                                      )
        myfile = File.new(myfileName, "w")
        Marshal.dump(client, myfile)
        logger.debug "dumped client to file - after creating fresh client with refresh_token"
        myfile.close
        logger.debug "4-client: " + client.inspect
      end
    end
    logger.debug "----------about to search printers-----------------------"
    printers = client.printers.all
    #logger.debug "printers: " + printers.inspect
    printers.each do |p|
      logger.debug "******printer-  id: " + p.id + "   name: " + p.name
      if p.name.downcase.include? "brother"
        printer_id = p.id
      end
    end
    logger.debug "printer_id: " + printer_id.inspect
    
    ###logger.debug "----------about to send a print-----------------------"
    ###my_printer = client.printers.find(printer_id)
    ###logger.debug "myprinter: " + my_printer.inspect
    ###my_printer.print(content: "<h1>This is a test print from the controller</h1>",
    ###                 content_type: "text/html")
  end  
  
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/admin.html.erb
<h1>Application Administration and Maintenance</h1>
<p><b><%= link_to 'Admin', shop_admin_path %></b><br>
This page.</p>

<p><b><%= link_to 'Counter', shop_counter_path %></b><br>
Provide the counter view: Where orders are placed.</p>

<p><b><%= link_to 'Brewster', shop_new_path %></b><br>
Provide the brewster view: Where orders are filled.</p>

<p><b><%= link_to 'Coffee', shop_coffee_path %></b><br>
Provide the coffee maker view: What needs to be made. This is a cut down version of the brewster view</p>

<p><b><%= link_to 'Check', shop_check_path %></b><br>
Provide the Check view: Display drinks that are ordered or ready.</p>

<p><b><%= link_to 'Ready', shop_ready_path %></b><br>
Provide the Ready view: Display drinks that are ready.</p>

<p><b><%= link_to 'Manage Orders', shop_orders_path %></b><br>
Provide capability to view, edit and remove orders. This is not a general user function but can be use to rectify some mistakes.</p>

<p><b><%= link_to 'Manage People', people_path %></b><br>
Provide capability to change the name of a person.</p>

<p><b><%= link_to 'Manage Buttons', buttons_path %></b><br>
Provide capability to manage the drink buttons - their names and relationships.</p>

<p><b><%= link_to 'Manage Drinks', drinks_path %></b><br>
DEPRECIATED -   Provide capability to manage the drink names.</p>

app/views/shops/check.html.erb
<!--
<h1 id="readyorders" style="display: none;">Orders ready for pickup</h1>
-->
<!--
<img id="setbackgroundimage" />
<%= image_tag('IMG_2284.JPG', style: "height: 30px; width: 30px") %>
-->
<div id="pageCheck"></div>
<div id="statusSelect">
  <% @statusList.each do |sl| %>
    <input id=<%= sl %> type="checkbox" checked >
  <% end %>
</div>
<% scrollText = "" %>
  <table id="orderstablet">
    <tbody id="orderstable">
      <% @readyorders.each do |order| %>
            <% className = "counterstatus" + order.status %>
            <!-- <tr id=t<%= order.id %> <%= className %>> -->
            <tr id=t<%= order.id %> class="<%= className %>">
              <td>
                <i class="new-icon fas fa-minus"></i>
                <i class="ready-icon fas fa-check"></i>
              </td>
              <td style="display: none;"><%= order.id %></td>
              <td class="content"><i class="fas fa-hiking mr-2 hideme"></i>
                <div><%= order.person.name %></div>
                <div class="small-text"><%= order.drink %></div>
              </td>
              <td><i class="fas fa-coffee mr-2 hideme"></i></td>
              <td style="display: none;"><%= order.quantity %></td>
              <td style="display: none;"><%= order.status %></td>
            </tr>
            <% if order.status == "ready" then
                 if scrollText.length > 0 then 
                   scrollText = scrollText + " - "
                 end
                 scrollText = scrollText + order.person.name
               end
      end %>
    </tbody>
  </table>

<% scrollText = scrollText #+ "--1--" + scrollText + "--2--" + scrollText %> 

<!--
<div>
  <svg width="300" height="100" viewbox="0,0,300,100">
    <rect y="0" width="300" height="100" style="fill:rgb(255,255,255);stroke-width:1;stroke:rgb(0,0,0)" />
  </svg>

  <svg width="300" height="100" viewBox="0 0 300  100">
    <rect y="0" width="300" height="100" style="fill:rgb(255,255,255);stroke-width:1;stroke:rgb(0,0,0)" />
    <text x="" y="50">
      This is my text.
      <animate attributeName="x" from "0" to="100" dur="5s" repeatCount="indefinite">
    </text>
  </svg>
</div>

<div>
  <svg width="300" height="100" viewBox="0 0 300  100">
    <ellipse cx="50" cy="50" rx="" ry="50">
      <animate attributeName="rx" from "0" to="50" dur="10s" repeatCount="indefinite">
    </ellipse>
  </svg>
</div>

<div>
  <svg viewbox="0,0,300,100" id="scrollText">
    <rect y="35" width="300" height="20" style="fill:rgb(255,255,255);stroke-width:3;stroke:rgb(0,0,0)" />
    <text x="" y="50">
      This is my text.
      <animate attributeName="x" from "0" to="400" dur="10s" repeatCount="indefinite">
    </text>
  </svg>
</div>
-->

<!--
<div id=scrollme>This is testing text</div>
-->
<!--
<div id=scrollme><%= scrollText %></div>
-->
<script type="text/javascript">
    selectStatusTable();
</script>

app/views/shops/coffee.html.erb
<div class="button floating-button floating-button-left-two">
  <%= link_to 'Admin', shop_admin_path %><i class="fas fa-angle-right ml-2"></i>
</div>
<div class="button floating-button floating-button-left">
  <%= link_to 'Counter', shop_counter_path %><i class="fas fa-angle-right ml-2"></i><br>
</div>


<div class="orders-container">
  <div class="orders-left-coffee">
    <h2 class="orange">New Orders</h2>
    <div id="sumorders">Test</div>
  </div>
  <div class="orders-right-coffee" style="display: none;">
    <div id="statusSelect">
      <b class="mr-3">Show</b><b>-</b>
      <input id=new type="checkbox" checked onclick="selectStatusBoth();" >
      <label for="new" class="new"><fa-icon class="fas fa-surprise mr-1"></fa-icon>new</label>
  
      <input id=ready type="checkbox" checked onclick="selectStatusBoth();" >
      <label for="ready" class="ready"><fa-icon class="fas fa-stopwatch mr-1"></fa-icon>ready</label>
  
      <input id=done type="checkbox" checked onclick="selectStatusBoth();" >
      <label for="done" class="done"><fa-icon class="fas fa-check mr-1"></fa-icon>done</label>
    </div>
    
    <div id="orders">
      <% @orders.each do |order| %>
        <% #byebug %>
        <div class="list-item <%= order.status %>" id=<%= order.id %>>
            <div class="list-item-content">
                <span style="display: none;"><%= order.id %></span>
                <div class="w-50 d-flex">
                  <span class="d-flex align-items-center">
                    <i class="fas fa-hiking"></i>
                    <span class="ml-2"><%= order.person.name %></span>
                  </span>
                  <span class="ml-3 d-flex align-items-center">
                    <i class="fas fa-coffee"></i>
                    <span class="ml-2"><%= order.drink %></span>
                  </span>
                </div>
                <span style="display: none;"><%= order.quantity %></span>
                <% #byebug %>
  
                <div class="ml-auto selection-container">
                    <div id="<%= order.id %>_new" class="new-radio-button counterbuttonnew" onclick="orderUpdate(this);">
                        <i class="fas fa-surprise"></i>
                        <span>New</span>
                    </div>
                    <div id="<%= order.id %>_ready" class="ready-radio-button counterbuttonready" onclick="orderUpdate(this);">
                        <i class="fas fa-stopwatch"></i>
                        <span>Ready</span>
                    </div>
                    <div id="<%= order.id %>_done" class="done-radio-button counterbuttondone" onclick="orderUpdate(this);">
                        <i class="fas fa-check"></i>
                        <span>Done</span>
                    </div>
                </div>
                
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
    selectStatusBoth();
</script>

app/views/shops/counter.html.erb
<p id="notice"><%= notice %></p>
<div class="button floating-button floating-button-right">
    <%= link_to 'Brewster', shop_new_path %><i class="fas fa-angle-right ml-2"></i><br>
</div>
<div class="button floating-button floating-button-right-two">
    <%= link_to 'Admin', shop_admin_path %><i class="fas fa-angle-right ml-2"></i>
</div>



<div class="container">
    <div class="left-container">
    <div class="search-container">
        <div class="input-group">
            <span class="search-icon fas fa-search"></span>
            <input class="search-bar" type="text" id="personInput" autocomplete="off" onkeyup="counterFilterPeople()" placeholder="Search" title="Type in characters to reduce name list">
            <!-- This span below is the clear button dad -->
            <span id=buttonClearFilter role="button" class="clear-button fas fa-times hideme" onclick="clearFilter();"></span>
        </div>
        <span id="buttonAddPerson" role="button" class="search-button hideme" onclick="counterAddPerson();">New Person</span>
        <div id="showAdd" onclick="counterAddPerson();" style="display: none;">Add this Person</div>
    </div>    
                <ul id="myPeopleUL">
        <% @people.each do |person| %>
            <% if person.lastdrink then %> 
                <li id=<%= person.id %> lastdrink="<%= person.lastdrink %>" onclick="counterSelectPerson(this);"><%= person.name %></li>
            <% else %>
                <li id=<%= person.id %> onclick="counterSelectPerson(this);"><%= person.name %></li>
            <% end %>
        <% end %>
    </ul>
    </div><!--
    --><div class="right-container">
        <div id="drinkarea">
            <div id="grpDrinks" class="drinks-column">
                <h2>Drink</h2>
    <% 
                @buttons.each do |b|
                    if b.group == "Drink" then
                        enablearray ="b" + b.enable.split(/ /).join(", b")
                        #byebug
     %>                 <button class="drinkbutton" data-enable="<%= enablearray %>"><%= b.name %></button>
    <%              end
               end
    %><!--
             --><button id="other" class="drinkbutton" data-enable="otherInput">Other</button>
            </div><!--
            --><div id="grpoptionsgroups" class="grpoptionsgroups">
    <% 
                currentGroup = ""
                @buttons.each do |b|
                    if b.group != "Drink" then
                        if b.group != currentGroup then
                            if currentGroup != "" then
    %>
                                </div>
    <%
                            end
                            currentGroup = b.group
    %><!--
                            --><div id="grpoptions" class="grpoptionsbutton hidemegrp">
                                <h2><%= b.group %></h2>
    <%
                        end
    %>
                        <button id="<%= "b" + b.id.to_s %>" class="optionsbutton hideme"><%= b.name %></button>
    <%
                    end
    %>
    <%
               end
               if currentGroup != "" then
    %>
                 </div><!--
                 
    --><%
               end
    %><!--
               --><div id="grpoptions" class="grpoptionsbutton hidemegrp">
                   <h2>Other</h2>
                   <input id="otherInput" class="optionsbutton hideme" type="text" placeholder="Type in your drink description" title="Drink Description">
               </div>
            </div>
        </div>    
    </div><!--
    --><div class="far-right-container">
        <div class="flex">
          <i class="fas fa-hiking ml-1"></i>
            <span class="ml-2" id=myPersonName> </span> 
            <span id=myPersonId style="display: none;"></span>
        </div>
        <div class="mt-2 flex">
            <i class="fas fa-coffee"></i>
            <span class="ml-2" id=myDrinkName> </span>
        </div>
        <div id="submitConfirm" class="button submit-button mt-2" style="display: none;">
            Order submitted
        </div>
        <div id="submitOrder" class="button b-orange submit-button mt-2" onclick="counterSubmitOrder();" style="display: none;">
            Submit order
        </div>
    </div>
    
    <!--<div id="submitOrder" class="button" onclick="counterSubmitOrder();" style="display: none;">Submit this order</div> -->
</div>

app/views/shops/new.html.erb
<div class="button floating-button floating-button-left-two">
  <%= link_to 'Admin', shop_admin_path %><i class="fas fa-angle-right ml-2"></i>
</div>
<div class="button floating-button floating-button-left">
  <%= link_to 'Counter', shop_counter_path %><i class="fas fa-angle-right ml-2"></i><br>
</div>


<div class="orders-container">
  <div class="orders-left">
    <h2 class="orange">New Orders</h2>
    <div id="sumorders">Test</div>
  </div>
  <div class="orders-right">
    <div id="statusSelect">
      <b class="mr-3">Show</b><b>-</b>
      <input id=new type="checkbox" checked onclick="selectStatusBoth();" >
      <label for="new" class="new"><fa-icon class="fas fa-surprise mr-1"></fa-icon>new</label>
  
      <input id=ready type="checkbox" checked onclick="selectStatusBoth();" >
      <label for="ready" class="ready"><fa-icon class="fas fa-stopwatch mr-1"></fa-icon>ready</label>
  
      <input id=done type="checkbox" checked onclick="selectStatusBoth();" >
      <label for="done" class="done"><fa-icon class="fas fa-check mr-1"></fa-icon>done</label>
    </div>
    
    <div id="orders">
      <% @orders.each do |order| %>
        <% #byebug %>
        <div class="list-item <%= order.status %>" id=<%= order.id %>>
            <div class="list-item-content">
                <span style="display: none;"><%= order.id %></span>
                <div class="w-50 d-flex">
                  <span class="d-flex align-items-center">
                    <i class="fas fa-hiking"></i>
                    <span class="ml-2"><%= order.person.name %></span>
                  </span>
                  <span class="ml-3 d-flex align-items-center">
                    <i class="fas fa-coffee"></i>
                    <span class="ml-2"><%= order.drink %></span>
                  </span>
                </div>
                <span style="display: none;"><%= order.quantity %></span>
                <% #byebug %>
  
                <div class="ml-auto selection-container">
                    <div id="<%= order.id %>_new" class="new-radio-button counterbuttonnew" onclick="orderUpdate(this);">
                        <i class="fas fa-surprise"></i>
                        <span>New</span>
                    </div>
                    <div id="<%= order.id %>_ready" class="ready-radio-button counterbuttonready" onclick="orderUpdate(this);">
                        <i class="fas fa-stopwatch"></i>
                        <span>Ready</span>
                    </div>
                    <div id="<%= order.id %>_done" class="done-radio-button counterbuttondone" onclick="orderUpdate(this);">
                        <i class="fas fa-check"></i>
                        <span>Done</span>
                    </div>
                </div>
                
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>



<!--
<hr/>

<table>
  <thead>
    <tr>
      <th style="display: none;">Id</th>
      <th>Person</th>
      <th>Drink</th>
      <th style="display: none;">Quantity</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody id="orderstable">
    <% @orders.each do |order| %>
      <% #byebug %>
      <tr id=<%= 't' + order.id.to_s %>>
        <% if order.status == "new" then %>
          <td style="display: none;"><%= order.id %></td>
          <td class="counterstatusnew"><%= order.person.name %></td>
          <td class="counterstatusnew"><%= order.drink %></td>
          <td style="display: none;"><%= order.quantity %></td>
          <td class="counterstatusnew"><%= order.status %></td>
        <% elsif order.status == "ready" then %>
          <td style="display: none;"><%= order.id %></td>
          <td class="counterstatusready"><%= order.person.name %></td>
          <td class="counterstatusready"><%= order.drink %></td>
          <td style="display: none;"><%= order.quantity %></td>
          <td class="counterstatusready"><%= order.status %></td>
        <% else %>
          <td style="display: none;"><%= order.id %></td>
          <td class="counterstatusdone"><%= order.person.name %></td>
          <td class="counterstatusdone"><%= order.drink %></td>
          <td style="display: none;"><%= order.quantity %></td>
          <td class="counterstatusdone"><%= order.status %></td>
        <% end %>
        <td id="<%= 't' + order.id.to_s %>_new" class="counterbuttonnew" onclick="orderUpdate(this);">New</td>
        <td id="<%= 't' + order.id.to_s %>_ready" class="counterbuttonready" onclick="orderUpdate(this);">Ready</td>
        <td id="<%= 't' + order.id.to_s %>_done" class="counterbuttondone" onclick="orderUpdate(this);">Done</td>
      </tr>
    <% end %>
  </tbody>
</table>
-->
<!--
<br>
<div id="statusSelect">
  <b>Show: </b>
  <% @statusList.each do |sl| %>
    <% if sl == "new" || sl == "ready" then %>
      <input id=<%= sl %> type="checkbox" checked onclick="selectStatusBoth();" > <%= sl %>
    <% else %>
      <input id=<%= sl %> type="checkbox" unchecked onclick="selectStatusBoth();" > <%= sl %>
    <% end %>
  <% end %>
</div>
-->
<script type="text/javascript">
    selectStatusBoth();
</script>

app/views/shops/orders.html.erb
<h1 id="allorders" >Orders - Management Purposes Only
<button><%= link_to 'counter', shop_counter_path %></button>
<button><%= link_to 'brewster', shop_new_path %></button><br>
</h1>
<div id="statusSelect">
  <input id="new" name="new" type="checkbox" checked onclick="selectStatusTable();" >
  <label for="new">new</label>
  <input id="ready" name="ready" type="checkbox" checked onclick="selectStatusTable();" >
  <label for="ready">ready</label>
  <input id="done" name="done" type="checkbox" checked onclick="selectStatusTable();" >
  <label for="done">done</label>
</div>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Person</th>
      <th>Drink</th>
      <th>Quantity</th>
      <th>Status</th>
      <th>To New</th>
      <th>To Ready</th>
      <th>To Done</th>
      <th>Day</th>
      <th>Created</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody id="orderstable">
    <% @orders.each do |order| %>
      <tr id=<%= 't' + order.id.to_s %>>
        <td><%= order.id %></td>
        <td><%= order.person.name %></td>
        <td><%= order.drink %></td>
        <td><%= order.quantity %></td>
        <td><%= order.status %></td>
        <td id="<%= 't' + order.id.to_s %>_new" onclick="orderUpdate(this);">To new</td>
        <td id="<%= 't' + order.id.to_s %>_ready" onclick="orderUpdate(this);">To ready</td>
        <td id="<%= 't' + order.id.to_s %>_done" onclick="orderUpdate(this);">To done</td>
        <td><%= order.day %></td>
        <td><%= order.created_at %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td onclick="destroyOrder(this);">Destroy</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orders for People', shop_counter_path %><br>
<%= link_to 'Orders Ready for Pickup', shop_ready_path %><br>
<%= link_to 'List all the people', people_path %>
<script type="text/javascript">
    selectStatus();
</script>

app/views/shops/print.html.erb
<h1>Printer Page</h1>

<div id="printlabel">
  This is a place holder only.
</div>

app/views/shops/printoauth.html.erb
<h1>Printer Page - oauth</h1>

<div id="printlabel">
  This is a place holder only.
</div>
<div id="print_button_container">Print button will be placed here</div>
<br>
<% if @authorize_url then %>
    <div id="authorize">
      <%= link_to 'Authorise connecting your printer', @authorize_url %>
    </div>
<% end %>